  
# use an official node runtime as the base image
FROM node:10.16.0-alpine

# set the (container) working directory
WORKDIR /app

# copy current (local) directory contents into the container
COPY . /app

# To handle 'not get uid/gid' build error
RUN npm config set unsafe-perm true

# upgrade npm and install dependencies
RUN npm install -g create-react-app && npm install

# run when the container launches
CMD ["npm", "start"]
